### ISSUE TITLE
Unit, integration tests failed after merge

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#455]
Hi Juvid!

The unit and integration tests failed when we merged with master -- there was some other branch that carried forward the "bad" vujson.py date, the last one that you fixed earlier today.  It's a small hit that only touched a couple of files, like this morning.  You may still have the fix somewhere, and we just need to figure out how to apply it.

To ensure we (this one's on me as much as on you) don't overwrite it later with a different merge, please create the fix branch off the latest/current `master` when you see this.  To view the issue, execute:

## Latest county and hospital data
```bash
./countyraid
```

## Latest predictions
```bash
./crystalball
```

## Generate the VirusTrack data feed, local only, patched:
```bash
./refreshdata local patch
```

When you're done, before you commit to your branch, please run these tests and ensure they pass:
```bash
make test && ./refresh local patch
```
I'll do the same thing during review, then right after approval.

Thanks and cheers!

**Comment by pr3d4t0r** [comment]
## Complete files list (short!)
```bash
grep -lrE 'TODO.*455" ./work/*
```

## Error sample

Thank goodness is a single error, not a lot of chasing around.  The issue is in calls to one or more functions in `vujson.py`.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 432, in _convert_listlike_datetimes
    values, tz = conversion.datetime_to_datetime64(arg)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/work/covidvu/pipeline/vujson.py", line 320, in <module>
    _ = parseCSSE(argument)
  File "/home/jovyan/work/covidvu/pipeline/vujson.py", line 272, in parseCSSE
    casesBoats = _getStateCounts(casesBoats, target)
  File "/home/jovyan/work/covidvu/pipeline/vujson.py", line 221, in _getStateCounts
    cases.index = pd.to_datetime(cases.index, format='%m/%d/%Y')
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 738, in to_datetime
    result = convert_listlike(arg, format)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 435, in _convert_listlike_datetimes
    raise e
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 400, in _convert_listlike_datetimes
    arg, format, exact=exact, errors=errors
  File "pandas/_libs/tslibs/strptime.pyx", line 142, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data '1/22/20' does not match format '%m/%d/%Y' (match)
[Error 17] - generateVirusUpdateJSONFiles - failed
```

**Comment by jaryaman** [comment]
Ok I think JH simply homologised their date formats last night from %m/%d/%Y or %m/%d/%y to strictly %m/%d/%y. Should be a simple fix.
